---
markdown: kramdown
highlighter: rouge
title: Ford Higgins' Blog
tagline: Musings on data, basketball, books, etc.
description: Musings on data, basketball, books, etc.
url: http://fordhiggins.com/
baseurl: ''
author:
  name: Ford Higgins
  url: https://twitter.com/wfordh
paginate: 5
exclude:
- README.md
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: fordhiggins
theme: jekyll-theme-hydeout
